# Generated by Django 4.2.4 on 2023-11-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watclist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watclist',
            new_name='watchlist',
        ),
    ]
